// src/lib/components/Video.svelte
<script lang="ts">
	import type { VideoProps } from '$lib/types';

	let { src, backgroundColor, aspectWidth, aspectHeight }: VideoProps = $props();
</script>

<div
	style="position: relative; background-color: {backgroundColor}; padding-bottom: {(aspectHeight /
		aspectWidth) *
		100}%;"
>
	<video
		class="absolute left-0 top-0 h-full w-full object-cover"
		muted
		playsinline
		preload="metadata"
		loop
		disablepictureinpicture
		disableremoteplayback
		autoplay
		controls={false}
	>
		<source type="video/mp4" {src} />
	</video>
</div>

// src/components/Video.tsx
export type VideoProps = {
  src: string;
  aspectWidth: number;
  aspectHeight: number;
  backgroundColor: string;
};
export function Video({
  src,
  backgroundColor,
  aspectHeight,
  aspectWidth,
}: VideoProps) {
  return (
    <div
      style={{
        position: 'relative',
        backgroundColor,
        paddingBottom: `${(aspectHeight / aspectWidth) * 100}%`,
      }}
    >
      <video
        className="absolute w-full h-full top-0 left-0 object-cover"
        muted
        playsInline
        preload="metadata"
        loop
        disablePictureInPicture
        disableRemotePlayback
        autoPlay
        controls={false}
      >
        <source type="video/mp4" src={src} />
      </video>
    </div>
  );
}
