// src/routes/work/[slug]/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import Layout from '$lib/components/Layout.svelte';
	import Divider from '$lib/components/Divider.svelte';
	import MediaCover from '$lib/components/MediaCover.svelte';
	import Video from '$lib/components/Video.svelte';
	import TextAnimationFadeIn from '$lib/components/TextAnimationFadeIn.svelte';
	import TextAnimationLineByLine from '$lib/components/TextAnimationLineByLine.svelte';
	import TechChips from '$lib/components/TechChips.svelte';
	import type { PageProps } from './$types';

	let { data }: PageProps = $props();
	let { study, studyIndex, nextStudy } = $derived(data);
</script>

<Layout>
	<section class="content-section mt-12">
		<Divider />
		<div class="relative py-16">
			<span class="absolute top-6 text-tiny">{`0${studyIndex + 1}/`}</span>
			<h1 class="leading-none">
				<TextAnimationLineByLine text={study.title} />
			</h1>
			<p class="base max-w-2xl pt-6">
				<TextAnimationFadeIn>{study.tagline}</TextAnimationFadeIn>
			</p>
		</div>
		<Divider />
		<div class="flex flex-col gap-y-4 py-6 text-sm sm:flex-row">
			<div class="sm:w-1/3">
				<span class="mb-1 block text-tiny">Client</span>
				{study.meta.client}
			</div>
			<div class="sm:w-1/3">
				<span class="mb-1 block text-tiny">Role</span>
				{study.meta.role}
			</div>
			<div class="sm:w-1/3">
				<span class="mb-1 block text-tiny">Period</span>
				{study.meta.period}
			</div>
		</div>
		<Divider />
	</section>

	<section class="content-section mt-16">
		<div class="relative mx-auto max-w-5xl overflow-hidden">
			<MediaCover />
			{#if !study.video}
				<img src={study.image.src} alt={study.image.alt} loading="lazy" />
			{:else}
				<Video
					src={study.video.src}
					aspectHeight={study.video.aspectHeight}
					aspectWidth={study.video.aspectWidth}
					backgroundColor={study.video.backgroundColor}
				/>
			{/if}
		</div>
	</section>

	<section class="content-section mb-24 mt-24">
		<div class="mx-auto max-w-2xl">
			{#each study.sections as section (section.heading)}
				<div class="mb-16">
					<h2 class="h3 mb-4">
						<TextAnimationFadeIn>{section.heading}</TextAnimationFadeIn>
					</h2>
					{#each section.paragraphs as paragraph, i (i)}
						<p class="mb-4 text-base">
							<TextAnimationFadeIn intersectionOptions={{ threshold: 0 }}>
								{paragraph}
							</TextAnimationFadeIn>
						</p>
					{/each}
				</div>
			{/each}
			<div class="mb-16">
				<h2 class="h3 mb-4">Technologies</h2>
				<TechChips technologies={study.technologies} />
			</div>
			{#if study.meta.link}
				<div class="mb-16">
					<!-- eslint-disable svelte/no-navigation-without-resolve -- study.meta.link.href is always an external URL -->
					<a
						class="button-lg inline-block"
						href={study.meta.link.href}
						target="_blank"
						rel="noreferrer"
					>
						Visit {study.meta.link.label} &#8599;
					</a>
					<!-- eslint-enable svelte/no-navigation-without-resolve -->
				</div>
			{/if}
		</div>
	</section>

	<section class="content-section mb-32">
		<Divider class="mb-7" />
		<div class="flex items-baseline justify-between">
			<a href={resolve('/')} class="text-sm font-medium">&#8592; All work</a>
			<a href={resolve('/work/[slug]', { slug: nextStudy.slug })} class="text-sm font-medium">
				Next: {nextStudy.title} &#8594;
			</a>
		</div>
	</section>
</Layout>

// src/pages/work/[slug].tsx
import { GetStaticPaths, GetStaticProps } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Layout } from '../../components/Layout';
import { Divider } from '../../components/Divider';
import { MediaCover } from '../../components/MediaCover';
import { Video } from '../../components/Video';
import { TextAnimationFadeIn } from '../../components/TextAnimationFadeIn';
import { TextAnimationLineByLine } from '../../components/TextAnimationLineByLine';
import { TechChips } from '../../components/TechChips';
import { caseStudies, getCaseStudy } from '../../data/caseStudies';

type WorkDetailProps = {
  slug: string;
};

export default function WorkDetail({ slug }: WorkDetailProps) {
  const study = getCaseStudy(slug);
  if (!study) return null;

  const studyIndex = caseStudies.findIndex((s) => s.slug === slug);
  const nextStudy = caseStudies[(studyIndex + 1) % caseStudies.length];

  return (
    <Layout>
      <section className="content-section mt-12">
        <Divider />
        <div className="relative py-16">
          <span className="absolute text-tiny top-6">{`0${
            studyIndex + 1
          }/`}</span>
          <h1 className="leading-none">
            <TextAnimationLineByLine>{study.title}</TextAnimationLineByLine>
          </h1>
          <p className="base pt-6 max-w-2xl">
            <TextAnimationFadeIn>{study.tagline}</TextAnimationFadeIn>
          </p>
        </div>
        <Divider />
        <div className="flex flex-col sm:flex-row gap-y-4 py-6 text-sm">
          <div className="sm:w-1/3">
            <span className="block text-tiny mb-1">Client</span>
            {study.meta.client}
          </div>
          <div className="sm:w-1/3">
            <span className="block text-tiny mb-1">Role</span>
            {study.meta.role}
          </div>
          <div className="sm:w-1/3">
            <span className="block text-tiny mb-1">Period</span>
            {study.meta.period}
          </div>
        </div>
        <Divider />
      </section>

      <section className="content-section mt-16">
        <div className="relative overflow-hidden max-w-5xl mx-auto">
          <MediaCover />
          {!study.video && (
            <Image
              src={study.image.src}
              alt={study.image.alt}
              layout="responsive"
              sizes=""
            />
          )}
          {study.video && (
            <Video
              src={study.video.src}
              aspectHeight={study.video.aspectHeight}
              aspectWidth={study.video.aspectWidth}
              backgroundColor={study.video.backgroundColor}
            />
          )}
        </div>
      </section>

      <section className="content-section mt-24 mb-24">
        <div className="max-w-2xl mx-auto">
          {study.sections.map((section) => (
            <div key={section.heading} className="mb-16">
              <h2 className="h3 mb-4">
                <TextAnimationFadeIn>{section.heading}</TextAnimationFadeIn>
              </h2>
              {section.paragraphs.map((paragraph, i) => (
                <p key={i} className="text-base mb-4">
                  <TextAnimationFadeIn interSectionOptions={{ threshold: 0 }}>
                    {paragraph}
                  </TextAnimationFadeIn>
                </p>
              ))}
            </div>
          ))}
          <div className="mb-16">
            <h2 className="h3 mb-4">Technologies</h2>
            <TechChips technologies={study.technologies} />
          </div>
          {study.meta.link && (
            <div className="mb-16">
              <a
                className="button-lg inline-block"
                href={study.meta.link.href}
                target="_blank"
                rel="noreferrer"
              >
                Visit {study.meta.link.label} &#8599;
              </a>
            </div>
          )}
        </div>
      </section>

      <section className="content-section mb-32">
        <Divider className="mb-7" />
        <div className="flex justify-between items-baseline">
          <Link href="/">
            <a className="text-sm font-medium">&#8592; All work</a>
          </Link>
          <Link href={`/work/${nextStudy.slug}`}>
            <a className="text-sm font-medium">
              Next: {nextStudy.title} &#8594;
            </a>
          </Link>
        </div>
      </section>
    </Layout>
  );
}

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: caseStudies.map((study) => ({ params: { slug: study.slug } })),
  fallback: false,
});

export const getStaticProps: GetStaticProps<WorkDetailProps> = async ({
  params,
}) => ({
  props: { slug: params!.slug as string },
});
