// src/components/DividerAnimated.tsx
import { CSSProperties } from 'react';
import { motion } from 'framer-motion';
import { useHasBeenInView } from '../utils/useHasBeenInView';

export function DividerAnimated({
  className,
  style,
}: {
  className?: string;
  style?: CSSProperties;
}) {
  const { hasBeenInView, ref } = useHasBeenInView({});

  return (
    <motion.div
      ref={ref}
      className={`${className} bg-text`}
      animate={hasBeenInView ? 'visible' : 'hidden'}
      variants={variants}
      style={{
        height: '1px',
        ...style,
      }}
    />
  );
}

const variants = {
  hidden: {
    width: '0%',
    transition: { ease: [0.455, 0.03, 0.515, 0.955], duration: 0.85 },
  },
  visible: {
    width: '100%',
    transition: { ease: [0.455, 0.03, 0.515, 0.955], duration: 0.85 },
  },
};

// src/lib/components/DividerAnimated.svelte
<script lang="ts">
	import { inView } from '$lib/actions/inView';

	let { class: className = '' }: { class?: string } = $props();

	let hasBeenInView = $state(false);
</script>

<div
	use:inView
	onhasbeeninview={() => (hasBeenInView = true)}
	class="{className} bg-text transition-[width] duration-[850ms] ease-[cubic-bezier(0.455,0.03,0.515,0.955)]"
	style="height: 1px; width: {hasBeenInView ? '100%' : '0%'};"
></div>
