// src/components/MediaCover.tsx
import { motion } from 'framer-motion';
import { useHasBeenInView } from '../utils/useHasBeenInView';

export function MediaCover() {
  const { ref, hasBeenInView } = useHasBeenInView({
    options: {
      threshold: 0.0,
    },
  });

  return (
    <motion.div
      ref={ref}
      animate={{
        x: hasBeenInView ? '100%' : 0,
        transition: {
          ease: [0.455, 0.03, 0.515, 0.955],
          duration: 0.5,
          delay: 0.8,
        },
      }}
      className="absolute w-full h-full bg-background"
      style={{ zIndex: 1 }}
    />
  );
}

// src/lib/components/MediaCover.svelte
<script lang="ts">
	import { inView } from '$lib/actions/inView';

	let hasBeenInView = $state(false);
</script>

<div
	use:inView
	onhasbeeninview={() => (hasBeenInView = true)}
	class="absolute h-full w-full bg-background transition-transform ease-[cubic-bezier(0.455,0.03,0.515,0.955)]"
	style="z-index: 1; transform: translateX({hasBeenInView
		? '100%'
		: '0'}); transition-duration: 500ms; transition-delay: 800ms;"
></div>
