// src/components/TechChips.tsx
export type TechChipsProps = {
  technologies: string[];
  className?: string;
};

export function TechChips({ technologies, className }: TechChipsProps) {
  return (
    <ul className={`flex flex-wrap gap-2 ${className ?? ''}`}>
      {technologies.map((technology) => (
        <li
          key={technology}
          className="text-tiny px-3 py-1 rounded-full"
          style={{ backgroundColor: '#CC7C5D', color: '#FAF8F5' }}
        >
          {technology}
        </li>
      ))}
    </ul>
  );
}

// src/lib/components/TechChips.svelte
<script lang="ts">
	let { technologies, class: className = '' }: { technologies: string[]; class?: string } =
		$props();
</script>

<ul class="flex flex-wrap gap-2 {className}">
	{#each technologies as technology (technology)}
		<li class="rounded-full px-3 py-1 text-tiny" style="background-color: #cc7c5d; color: #faf8f5;">
			{technology}
		</li>
	{/each}
</ul>
