// src/components/TextAnimationFadeIn.tsx
import { motion } from 'framer-motion';
import { ReactNode } from 'react';
import {
  useHasBeenInView,
  IntersectionOptions,
} from '../utils/useHasBeenInView';
type TextAnimationFadeInProps = {
  children: ReactNode;
  interSectionOptions?: IntersectionOptions;
};

export function TextAnimationFadeIn({
  children,
  interSectionOptions = { threshold: 0 },
}: TextAnimationFadeInProps) {
  const { ref, hasBeenInView } = useHasBeenInView({
    options: interSectionOptions,
  });

  return (
    <motion.span
      ref={ref}
      style={{ display: 'inline-block' }}
      initial="hidden"
      animate={hasBeenInView ? 'visible' : 'hidden'}
      variants={letterVariants}
    >
      {children}
    </motion.span>
  );
}

const letterVariants = {
  hidden: {
    y: 40,
    opacity: 0,
    transition: { ease: [0.455, 0.03, 0.515, 0.955], duration: 0.85 },
  },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      ease: [0.455, 0.03, 0.515, 0.955],
      duration: 0.75,
    },
  },
};

// src/lib/components/TextAnimationFadeIn.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { inView } from '$lib/actions/inView';

	let {
		children,
		intersectionOptions = { threshold: 0 }
	}: {
		children: Snippet;
		intersectionOptions?: IntersectionObserverInit;
	} = $props();

	let hasBeenInView = $state(false);
</script>

<span
	use:inView={intersectionOptions}
	onhasbeeninview={() => (hasBeenInView = true)}
	class="inline-block transition-[transform,opacity] ease-[cubic-bezier(0.455,0.03,0.515,0.955)]"
	style="transform: translateY({hasBeenInView ? 0 : 40}px); opacity: {hasBeenInView
		? 1
		: 0}; transition-duration: {hasBeenInView ? '750ms' : '850ms'};"
>
	{@render children()}
</span>
