// src/components/WorkItem.tsx
import Image from 'next/image';
import { MediaCover } from './MediaCover';
import { TextAnimationFadeIn } from './TextAnimationFadeIn';
import { TextAnimationLineByLine } from './TextAnimationLineByLine';
import { Video, VideoProps } from './Video';

export type WorkItemProps = {
  /**
   * Preferred image dimensions: 815 x 556
   */
  image: {
    src: any;
    alt: string;
  };
  video?: VideoProps;
  title: string;
  description: string;
  itemNumber: string;
};
export function WorkItem({
  image,
  title,
  description,
  video,
  itemNumber,
}: WorkItemProps) {
  return (
    <div className="relative flex justify-between flex-col workItemBreakpoint:flex-row py-24">
      <div className="flex flex-col justify-between w-full workItemBreakpoint:w-2/5">
        <span className="absolute text-tiny top-6">{itemNumber}</span>
        <h3 className="h1 leading-none -mt-2">
          <TextAnimationLineByLine>{title}</TextAnimationLineByLine>
        </h3>
        <p className="base pt-8">
          <TextAnimationFadeIn interSectionOptions={{ threshold: 0 }}>
            {description}
          </TextAnimationFadeIn>
        </p>
      </div>
      <div className="relative overflow-hidden w-full pt-16 workItemBreakpoint:pt-0 workItemBreakpoint:w-6/12">
        <MediaCover />
        {!video && (
          <Image src={image.src} alt={image.alt} layout="responsive" sizes="" />
        )}
        {video && (
          <Video
            src={video.src}
            aspectHeight={video.aspectHeight}
            aspectWidth={video.aspectWidth}
            backgroundColor={video.backgroundColor}
          />
        )}
      </div>
    </div>
  );
}

// src/lib/components/WorkItem.svelte
<script lang="ts">
	import MediaCover from './MediaCover.svelte';
	import TextAnimationFadeIn from './TextAnimationFadeIn.svelte';
	import TextAnimationLineByLine from './TextAnimationLineByLine.svelte';
	import Video from './Video.svelte';
	import type { CaseStudy } from '$lib/types';

	let {
		image,
		title,
		description,
		video,
		itemNumber,
		href
	}: {
		image: CaseStudy['image'];
		video?: CaseStudy['video'];
		title: string;
		description: string;
		itemNumber: string;
		href?: string;
	} = $props();
</script>

<div class="work-item:flex-row relative flex flex-col justify-between py-24">
	<div class="work-item:w-2/5 flex w-full flex-col justify-between">
		<span class="absolute top-6 text-tiny">{itemNumber}</span>
		<h3 class="h1 -mt-2 leading-none">
			<TextAnimationLineByLine text={title} />
		</h3>
		<div>
			<p class="base pt-8">
				<TextAnimationFadeIn intersectionOptions={{ threshold: 0 }}>
					{description}
				</TextAnimationFadeIn>
			</p>
			{#if href}
				<p class="pt-6">
					<TextAnimationFadeIn intersectionOptions={{ threshold: 0 }}>
						<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -- href is already resolved by the caller -->
						<a {href} class="text-sm font-medium underline underline-offset-4">
							Read case study &#8594;
						</a>
					</TextAnimationFadeIn>
				</p>
			{/if}
		</div>
	</div>
	<div class="work-item:w-6/12 work-item:pt-0 relative w-full overflow-hidden pt-16">
		<MediaCover />
		{#if !video}
			<img src={image.src} alt={image.alt} loading="lazy" />
		{:else}
			<Video
				src={video.src}
				aspectHeight={video.aspectHeight}
				aspectWidth={video.aspectWidth}
				backgroundColor={video.backgroundColor}
			/>
		{/if}
	</div>
</div>
